default: &default
    adapter: postgresql
    encoding: unicode
    host: db
    user: postgres
    password: postgres

development:
    <<: *default
    database: app_develop

test:
    <<: *default
    database: app_testing

production:
    <<: *default
    database: app_prod
